### PR TITLE
#32: Use ContextAPI

### LINKED ISSUE #32: refactor code to use the context api to share things like userstate easier

### PR DESCRIPTION
**Pull request by tu-tran**
Fixes #32

### CODE REVIEW

**Comment by tu-tran** [comment]
If the code is OK, I will start fixing the tests

**Comment by andersnylund** [comment]
Will take a look at it later tonight if I have time

**Comment by andersnylund** [comment]
I like this! Have not seen this in action before but looks like it's working. I give it a GO 👍🏼

**Comment by tu-tran** [comment]
> I like this! Have not seen this in action before but looks like it's working. I give it a GO 👍🏼

Yeah. And the test is the real pain :( Somehow it feels like there are much more tests than the code itself :(

**Comment by andersnylund** [comment]
@tu-tran I can help with the tests as I would really like to have this merged

**Comment by tu-tran** [comment]
> @tu-tran I can help with the tests as I would really like to have this merged

@andersnylund : That would be great... How would you wanna split ? :) (or you can go 100% if you are that excited too) :D

**Pull request closed without merging**
